services:
  app:
    image: samratmajumder/intellisurv_app:latest
    ports:
      - "5020:5020"
    volumes:
      - ./log:/var/log
      - ./log/app.log:/app/app.log
      - ./config_docker.ini:/app/config.ini
      - ./vidout:/app/vidout
      - ./vidout2:/app/vidout2
      - /mnt/nfs_share/vidout:/app/remote
      - ./.cid:/app/.cid
      - /etc/machine-id:/etc/machine-id
      - ./licdocker:/app/lic
      - tempvideos:/tempvideos
      - tempsnapshots:/tempsnapshots
      - ./uptimekdb:/app/uptimekdb
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - mariadb
      - redis
      - rabbitmq

  # aiprocessor:
  #   image: samratmajumder/intellisurv_aiprocessor:latest
  #   volumes:
  #     - ./log:/var/log
  #     - ./config_docker.ini:/app/config.ini
  #     - ./fire.pt:/app/fire.pt
  #     - ./weapon.pt:/app/weapon.pt
  #     - ./.cid:/app/.cid
  #     - /etc/machine-id:/etc/machine-id
  #     - ./known_faces_folder:/app/known_faces_folder
  #     - ./testvideos:/app/testvideos
  #   environment:
  #     - TZ=Asia/Kolkata
  #   depends_on:
  #     - mariadb
  #     - rabbitmq
  #     - redis

  recordingprocess:
    image: samratmajumder/intellisurv_recordingprocess:latest
    volumes:
      - ./log:/var/log
      - ./config_docker.ini:/app/config.ini
      - ./vidout:/app/vidout
      - ./vidout2:/app/vidout2
      - ./.cid:/app/.cid
      - /etc/machine-id:/etc/machine-id
      - ./licdocker:/app/lic
      - tempsnapshots:/tempsnapshots
    depends_on:
      - mariadb
      - redis
    environment:
      - TZ=Asia/Kolkata

  webglproxy:
    image: samratmajumder/intellisurv_webglproxy:latest
    ports:
      - "10399:10399"
      - "10400:10400"
    volumes:
      - ./log:/var/log
      - ./config_docker.ini:/app/config.ini
      - ./.cid:/app/.cid
      - /etc/machine-id:/etc/machine-id
      - ./licdocker:/app/lic
    environment:
      - TZ=Asia/Kolkata
    depends_on:
      - mariadb
      - redis

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
      - ./vidout:/var/vidout
      - tempvideos:/tempvideos
      - tempsnapshots:/tempsnapshots
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Kolkata

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: intellisurv
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    volumes:
      - ./dbdump:/var/lib/mysql
      - ./intellisurvdbdump.sql:/docker-entrypoint-initdb.d/intellisurvdbdump.sql

  redis:
    image: redis:latest
    command: [ "redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru" ]
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Kolkata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Kolkata

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "intellisurv" # Replace with your desired username
      RABBITMQ_DEFAULT_PASS: "intellisurv" # Replace with your desired password
      RABBITMQ_DEFAULT_VHOST: "/" # Replace with your desired vhost if needed\
      TZ: Asia/Kolkata

    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management interface (accessible at http://{YOUR_SERVER_IP}:15672)
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
      - "rabbitmq_log:/var/log/rabbitmq"

  uptimekmonitoring:
    image: samratmajumder/tnxtuptimekmonitoring:latest
    ports:
      - "9093:3001" # Default Uptime Kuma port
    volumes:
      - ./uptimekdb:/app/data
    environment:
      - UPTIME_KUMA_HIDE_HEADER=true
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true

volumes:
  rabbitmq_data:
  rabbitmq_log:
  tempvideos:
  tempsnapshots:


